#!/bin/bash


# Munge together all command line args.
MUNGED_AGRS=""

for i in "$@"
do
    MUNGED_ARGS+=" ${i}"
done

export LD_LIBRARY_PATH=/usr/lib/rng-tools/:/lib/:/usr/lib/

/usr/local/bin/rngd-deb ${MUNGED_AGRS}
